name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

jobs:
  formatting:
    name: Formatting & Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5.0.0
      - name: Set up JDK
        uses: actions/setup-java@v5.0.0
        with:
          distribution: 'zulu'
          java-version: 21
      - name: spotless
        run: ./gradlew spotlessCheck
      - name: detekt
        run: ./gradlew detekt

  sample-app:
    name: Sample App
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5.0.0
      - name: Set up JDK
        uses: actions/setup-java@v5.0.0
        with:
          distribution: 'zulu'
          java-version: 21
      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Assemble sample app
        run: |
          ./gradlew --stacktrace \
              app:assembleDebug

      - name: Run sample app unit tests
        run: |
          ./gradlew --stacktrace \
              app:testDebugUnitTest

  plugin:
    name: IntelliJ Plugin
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5.0.0
      - name: Set up JDK
        uses: actions/setup-java@v5.0.0
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Validate plugin project configuration
        run: ./gradlew --stacktrace compose-guard:check

      - name: Coverage report
        run: ./gradlew --stacktrace koverXmlReport koverVerify
